###########
# site.title

title:    'Pufferfish'
subtitle: 'CS 175: Reinforcement-based Minecraft 1.9+ PvP'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
